### ISSUE TITLE
OSError: [Errno 97] Address family not supported by protocol

### ISSUE THREAD

**Issue by bhairavmehta95** [duckietown/rpi-ros-kinetic-roscore#1]
When running:

`docker run --entrypoint=qemu-arm-static -it duckietown/rpi-ros-kinetic-roscore:master18 /bin/bash`

and then `source /opt/ros/kinetic/setup.bash && roscore`

I receive an error that ends with this:
OSError: [Errno 97] Address family not supported by protocol

I believe it's related to the one I had a few weeks back, from here:
https://github.com/rusi/duckietown.dev.land/issues/11

But I'm not sure if this change was made.

I am running Ubuntu x86.

**Comment by AndreaCensi** [comment]
no idea. Can you copy the entire error?

**Comment by bhairavmehta95** [comment]
```
root@9ec1739a1144:/# roscore
... logging to /root/.ros/log/6353ce12-cc16-11e8-aa26-0242ac110002/roslaunch-9ec1739a1144-160.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://9ec1739a1144:40005/
ros_comm version 1.12.13


SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.13

NODES

Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/__init__.py", line 306, in main
    p.start()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/parent.py", line 279, in start
    self.runner.launch()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/launch.py", line 657, in launch
    self._setup()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/launch.py", line 632, in _setup
    launched = self._launch_master()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/launch.py", line 397, in _launch_master
    validate_master_launch(m, self.is_core, self.is_rostest)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/launch.py", line 83, in validate_master_launch
    if not rosgraph.network.is_local_address(m.get_host()):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 175, in is_local_address
    local_addresses = ['localhost'] + get_local_addresses()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 218, in get_local_addresses
    for iface in netifaces.interfaces():
OSError: [Errno 97] Address family not supported by protocol
```

I am also getting this error when trying to launch the [Lane Following demo](https://github.com/duckietown/rpi-duckiebot-lanefollowing-demo) on Ubuntu as well.

**Comment by breandan** [comment]
Sorry @bhairavmehta95, I should have documented this somewhere. The fix for running this on x86 is:

`docker run --entrypoint=qemu3-arm-static --network=host -it duckietown/rpi-ros-kinetic-roscore:master18 /bin/bash -c "source /opt/ros/kinetic/setup.bash && roscore"`

@AndreaCensi Until Resin updates their [qemu fork](https://github.com/resin-io/qemu/issues/16), we'll need to do it this way in order to run `roscore` on x86. I'm going to add the instructions to the Duckumentation.

**Comment by breandan** [comment]
Alternatively, if you don't want to do the whole emulator thing, you can just run:

`docker run --network=host -it ros:kinetic-ros-base-xenial roscore`

**Comment by bhairavmehta95** [comment]
@breandan cool thank you! And yeah I've been developing mostly with the standard OSRF docker image, but just needed the duckietown version to test some things. Thanks again!

**Comment by AndreaCensi** [comment]
Re-opening until this is added to the manual.

**Comment by liampaull** [comment]
@breandan can you add in the manual?
